# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginViaFacebook():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_loginViaFacebook(self):
    self.driver.get("https://www.google.com/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.NAME, "q").send_keys("kabum")
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    element = self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > .rc .LC20lb")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > .rc .LC20lb").click()
    self.driver.find_element(By.LINK_TEXT, "LOGIN | CADASTRE-SE").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".btnFacebook").click()
    self.vars["win9971"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    element = self.driver.find_element(By.CSS_SELECTOR, ".ec-internal-promotion:nth-child(2)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#btn-fechar img").click()
  
